const type = {
  CHANGE_MV: 'CHANGE_MV',
  CHANGE_IFSHOWPLAYER: 'CHANGE_IFSHOWPLAYER',
  SET_SONG: 'SET_SONG',
  SET_SONGURL: 'SET_SONGURL',
  CHANGE_MUSICPLAYSTATE: 'CHANGE_MUSICPLAYSTATE'
}

export default type
